{
    'name': '雷達無人機視覺辨識平台',
    'version': '18.0.1.0.0',
    'category': 'Scientific',
    'summary': '低空小目標雷達 AI 驗證平台：micro-Doppler 訊號辨識 UAV 與鳥類',
    'author': 'CoolCold Tech',
    'website': 'https://radar.ksu.coolcold.com.tw',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'web', 'website'],
    'data': [
        'security/radar_security.xml',
        'security/ir.model.access.csv',
        'data/default_action.xml',
        'views/dataset_views.xml',
        'views/experiment_views.xml',
        'views/model_views.xml',
        'views/inference_views.xml',
        'views/hardware_views.xml',
        'views/dashboard_views.xml',
        'views/menu.xml',
        'views/landing_page.xml',
        'views/login_page.xml',
        'views/hide_branding.xml',
    ],
    'assets': {
        'web._assets_primary_variables': [
            ('after', 'web/static/src/scss/primary_variables.scss',
             'radar_drone_vision/static/src/scss/theme_variables.scss'),
        ],
        'web.assets_backend': [
            'radar_drone_vision/static/src/scss/theme_navbar.scss',
            'radar_drone_vision/static/src/js/navbar_active_tracker.js',
            'radar_drone_vision/static/src/js/dashboard.js',
            'radar_drone_vision/static/src/xml/dashboard.xml',
        ],
    },
    'application': True,
    'installable': True,
    'auto_install': False,
}
