[options]
admin_passwd = bio5234
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = radar_drone_vision
addons_path = /mnt/extra-addons
default_productivity_apps = True
proxy_mode = True
without_demo = all
